### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by wider-spider** [questbeat/QBImagePicker#63]
I've compiled the framework with default settings, imported it into my project (default iOS architecture). I do have two different Bridging-Header files for the App and its WatchKit Extension. I #import the framework in the App target only.
I got an Apple Mach-O Linker Warning:
missing required architecture x86_64 in file
... /Frameworks/QBImagePicker.framework/QBImagePicker (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_QBImagePickerController", referenced from:
      __TMaCSo23QBImagePickerController in GCFoto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas?

**Comment by questbeat** [comment]
Check that the framework is correctly linked and embedded in the app.

**Comment by wider-spider** [comment]
I am quite sure to do so.
Does it matter, that I build the Framework from within Xcode imported it as a regular Framework? I did not installed it via Pods. After some deep research I learned that Frameworks have to be Fat libraries including all platforms, which probably is/was not possible with Xcode.
I would prefer to use the Framework with the regular inline Framework handling - not via another tool like Pods…

**Comment by questbeat** [comment]
I think it doesn't matter.

Did you see the `QBImagePickerDemo` in the project?
Please check again your project settigs is like this:
http://gyazo.com/c57b45287495cda4ea9cb213c9cc415e

**Comment by wider-spider** [comment]
I see the QBImagePickerDemo in the project.
Indeed, I had not included the framework in Embedded Binaries.
Although it had changed nothing, the error stays the same (yes, I've done "clean" before the next build).

Does this might matter?
http://stackoverflow.com/questions/28774768/xcode-6-error-missing-required-architecture-i386-when-building-for-ios-simul

**Comment by questbeat** [comment]
> Does this might matter?
> http://stackoverflow.com/questions/28774768/xcode-6-error-missing-required-architecture-i386-when-building-for-ios-simul

Maybe...

Ideas:

1. Try [Carthage](https://github.com/Carthage/Carthage)
2. Copy source files into your project directly

**Comment by wider-spider** [comment]
Solved via cocoapods, finally.
After days of research and try-and-error I've become paranoid, because there are tons of header link error discussions out there.
The last mistake has been to not include the xcconfig in the test target as well, which will not happen on "pod install".
Shame on Apple that Framework export is not possible and therefore integration in a straight forward manner as well.

Thank you for your patience. Solved.

**Comment by roeik** [comment]
I am having the same problem, I think. And for the last two days I am trying to figure out how to use Carthage or cocapods, it doesn't work. I have tried everything. 
Why can't I just copy the frmework into the library like you do with any other framework (facebook, parse, etc)?  I don't get it! 
Can you please help me figure how to add this framework properly?

**Comment by luxis** [comment]
@roeik You should be able to just copy it into your project? That's how I use it..?

**Comment by roeik** [comment]
Well, I can’t. Usually this is what I do when I add a framework. BUt this frameworks need to be built on you local machine. After 3 days of research it turns out that If you compile it for one architecture (Device) you can’t run it on another architecture (simulator). There is a way to compile it for all architecture but I don’t know how to do it. 

Roei Kashi
www.motikashi.com <http://www.motikashi.com/>
+1 (213) 254 5052 <tel:%2B1%20%28213%29%20254%205052>
+972 (54) 3978094 <tel:%2B972%20%2854%29%203978094>
+41 79 9561477 <tel:%2B41%2079%209561477>
+852 63104732 <tel:%2B852%2063104732>
+66 83 711 6060 <tel:%2B66%2083%20711%206060>
+91 98334 55431 <tel:%2B91%2098334%2055431>


Need a Diamond? Contact Me! 

Have an iPhone? Search for iDiamonds <http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=301382577&mt=8> on the App Store <http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=301382577&mt=8> or visit www.idiamondsmobile.com <http://www.idiamondsmobile.com/> 

Skype: roeikashi  Google Talk: roeikashi@gmail.com <mailto:roeikashi@gmail.com> MSN: roeik@hotmail.com <mailto:roeik@hotmail.com>
Contact Me  <http://www.facebook.com/roeik>
 <http://www.facebook.com/roeik>

**Comment by roeik** [comment]
@luxis  Did you build the framework before you copied it? Or what exactly did you copy?
